### ISSUE TITLE
JSON Update Related Fixes 

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#133]
- [x] Atlas tab id does not match up with files ID. E.g. on atlas tab `Transition to Metastatic State: Lung Cancer, Pancreatic Cancer and Brain Metastasis` is HTA8. But if you search `HTA8_` in Files tab it instead shows the atlas name as `Omic and Multidimensional Spatial Atlas of Metastatic Breast Cancers`, which is HTA_9` on the atlas tab. See: https://data.humantumoratlas.org/explore?tab=atlas @adamabeshouse  (https://github.com/ncihtan/htan-portal/pull/144)

- [x] Download tab popup shows name of file (it should display the snyapseid for downloading) @onursumer 

- [x] On biospecimen tab `Atlas ID` shows up lowercase @adamabeshouse 

- [x] Undefined shows up in the all filters search @adamabeshouse (https://github.com/ncihtan/htan-portal/pull/144)

    <img width="239" alt="Screen Shot 2021-03-09 at 1 53 06 PM" src="https://user-images.githubusercontent.com/1334004/110522390-d6d04300-80de-11eb-9108-a93d331ecbc3.png">
   

- [x] In the assay type dropdown i only see `ScRNA-seqLevel1`, but there should be level 2 and 3. So something goes wrong with data type there. It would also be good to remove the `Level` postfix and just list the assay type. One can use the File Type filter instead to get the level @alisman @adamabeshouse 

- [x] Are the many missing values in the data or an issue with our transformations?

    
    
    <img width="317" alt="Screen Shot 2021-03-09 at 1 58 05 PM" src="https://user-images.githubusercontent.com/1334004/110522949-7e4d7580-80df-11eb-8e3f-f0005511334d.png">

    <img width="317" alt="Screen Shot 2021-03-09 at 1 57 25 PM" src="https://user-images.githubusercontent.com/1334004/110522905-7097f000-80df-11eb-8396-56fea59f4cdb.png">

    EDIT: Seems like it's Vanderbilt (might be imaging level 1), we should reach out to the center @inodb @vthorsson 

- [x] search for pancreas NOS in all filters ->  select -> crash @onursumer (seems fixed by #137)

@alisman @adamabeshouse @onursumer let's split these up at 2PM

**Comment by schultzn** [comment]
Here is some more feedback on names and displays.. looks great!!

- [ ]  - "Biospecimen" tab name should be "Biospecimens" to match the plural of the other tabs
- [ ]  - Can the Level in the assay type be separated by a space, e.g. "scRNA-seq Level 1"?
- [ ]  - and can the first letter of the assay type be lower case, e.g. "scRNA" instead of "ScRNA"?
- [ ]  - Atlases page: Switch column order: Lead Institution first, Atlas name second
- [ ]  - Does the Files tab need the atlas ID?
- [ ]  - Atlas ID should always be CAPS CAPS, HTAXX
- [ ]  - Remove Atlas colum from Files tab and replace with Atlas ID
- [ ]  - does the filename column need to show the full path, or is filename sufficient?
- [ ]  - can the filename column be wider?
- [ ]  - use a slightly larger font for the summary statistics on the files tab so that even the PIs can read it
- [ ]  - Order in the summary should be:

  - Atlases
  - Organs
  - Cancer Types
  - Cases
  - Biospeciments
  - Assays
  - Files

**Comment by onursumer** [comment]
> * [ ]   - does the filename column need to show the full path, or is filename sufficient?
> * [ ]   - can the filename column be wider?

we have a separate issue for these ones: #129

> * [ ]   - use a slightly larger font for the summary statistics on the files tab so that even the PIs can read it

oops, we thought we were targeting a younger user base :smile:

**Comment by schultzn** [comment]
> oops, we thought we were targeting a younger user base 😄

I only commented on behalf of the older PIs... you can make the font size smaller for me.

**Comment by onursumer** [comment]
> > oops, we thought we were targeting a younger user base 😄
> 
> I only commented on behalf of the older PIs... you can make the font size smaller for me.

@schultzn https://htan-portal-ne-git-fork-onursumer-increase-summary-font-415aea.vercel.app/explore?tab=file. Could you confirm that this version is PI readable? I mean on behalf of the older PIs 😉

**Comment by schultzn** [comment]
better, yes! @onursumer

**Comment by inodb** [comment]
This is done
