### ISSUE TITLE
Cancer stage = null says there are 7378 files but none show up

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#165]
When I click Null on the Cancer Stage filter, the filter says there are 7378 files but none show up:

<img width="1068" alt="Screen Shot 2021-03-18 at 2 53 12 PM" src="https://user-images.githubusercontent.com/67977813/111681751-fe6b8d80-87f9-11eb-8d3a-b58523855acd.png">

**Comment by alisman** [comment]
@inodb @elysekozlowski for stage, we are looking a property of the Case > Diagnosis data called "AJCCClinicalStage".  It turns out it basically never has any value.  It's either null or Not Reported.    
1. The choice of this property may have been arbitrary.  Like, I might have used it because it had the word stage in it.
2. If we expect this to be filled in as data matures, I guess we should figure out out how null values should show up, e.g.  "Not Defined" ?     Giving them a string value will allow us to filter them (which would fix this ticket).

**Comment by inodb** [comment]
@alisman hmm good find. Yeah seems like stage would be useful to have. Let's discuss with some more people to see if we should be more stringent about asking people to submit this information

**Comment by inodb** [comment]
But yeah in terms of the data portal: I think we probably want to remove stage for now since I doubt we'll be able to get that info by April. It might be nice to have a way to enable it easily again in the future

**Comment by alisman** [comment]
will do
