### ISSUE TITLE
WP Question re:  My Atlas

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#26]
This is just a question.  In the My Atlas page, I see something like:

![screenshot_303](https://user-images.githubusercontent.com/1009066/78403789-fdcaee80-75ca-11ea-827e-c20c3c4f91a3.png)

What/where does the content of that first text box go?

**Comment by alisman** [comment]
So, Atlases are just a category of WP Posts.  (I created this category as target for the custom fields, not wanting all posts in the system to have these fields).  The empty box is the post's content blob.  I didn't used it simply because it didn't seem to me there was any "main" text for the Atlas.  I suppose it could have been used for the overview text.  We can use it for that purpose if you want.

**Comment by ecerami** [comment]
ok. closing.
