### ISSUE TITLE
Conditionally hide data release links

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#31]
It's possible/likely that some atlases will not have data for the release.

So...

if at atlas has no Synapse ID, can we hide the "Data Release" link on this page?  https://htan-portal-nextjs.now.sh/data_releases

**Comment by ethansiegl** [comment]
Hi @alisman. How is the `data.json` associated with any particular atlas? Was expecting to find `hta1`, `hta2`, `hta3` etc id but I only see text labels which read `HTAN CenterA` and `HTAN CenterB`

**Comment by alisman** [comment]
@ethansiegl the top level keys in data.json serve as the "Synapse Id".  In order to associate them with Atlases in WP, we have to manually enter the Synapse ID field in the WP Atlas screen.  For this ticket, if there is no Synapse ID in WP data, we should hide the Atlas altogether on the data release page.  Let me know if this needs further explaination.

**Comment by ecerami** [comment]
Fixed.  closing..

**Comment by ecerami** [comment]
Closing...
