### ISSUE TITLE
Individual rows of clinical data should not have download links

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#34]
If you go here:  https://htan-portal-nextjs.now.sh/atlas/hta2

and, then click on clinical data, you see two rows of data.

If you scroll all the way to the right, you see download links for Synapse, e.g. 

![screenshot_358](https://user-images.githubusercontent.com/1009066/80620170-a24a2000-8a13-11ea-9c44-8051a02e24ca.png)

I believe this is due to a "downloadLink" in the JSON.

But... I don't think individual rows of data should not have a download link.  You should only be able to download all the clinical data in one go, e.g. by clicking the download button on the clinical data tab.

**Comment by milen-sage** [comment]
There are a couple of types of download links already in the json data:
- the key "downloadLink" for each data category, which points to *all* files/biosamples/patients in a particular category on Synapse
- the attribute "downloadLink" for each data row that points to the location of specific file/specimen/patient data on Synapse

I agree that the first would be more useful for people and since it is the same for all files perhaps we can place a "button/link" outside the table?

Do you think the file specific link is useful in each row? It does lead people to the specific object on Synapse, and from there to the dataset/folder containing the object.

**Comment by ecerami** [comment]
@milen-sage for all the tabs, we have a download button right next to the pull-down menu.

for biospecimen and clinical data, I don't think it's useful to have downloads for each row.

But, for derived data and imaging data, yes, we need the download/view links.

**Comment by milen-sage** [comment]
Great! Yes - sorry, the overall download button escaped my mind - in this case the link for that button is already in the json blob; it is the "downloadLink" for each category.

And yes, biospecimen and clinical data currently getting Synapse links was a mistake on my end; it will be corrected with the next PR today.

**Comment by milen-sage** [comment]
This has been resolved a few days ago and these links are no longer part of the data for biospecimen and clinical data (e.g. https://github.com/ncihtan/htan-portal/pull/35/files#diff-868ae2d65fb52e0bf680b28558a92a88R42)
