### ISSUE TITLE
Some Vanderbilt H&E Images are Missing Thumbnails + Minerva

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#437]
If I go to:  https://data.humantumoratlas.org/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+Vanderbilt%22%7D%2C%7B%22value%22%3A%22H%26E%22%2C%22label%22%3A%22H%26E%22%2C%22group%22%3A%22assayName%22%2C%22count%22%3A30%2C%22isSelected%22%3Afalse%7D%5D&tab=file#

Many of the H&E images have thumbnails and Minerva images.

But, several do not.  Is that a bug or a feature? :-)

**Comment by ecerami** [comment]
Seems to be a similar issue for Multiplex IF data.  

See: https://data.humantumoratlas.org/explore?selectedFilters=%5B%7B%22group%22%3A%22AtlasName%22%2C%22value%22%3A%22HTAN+Vanderbilt%22%7D%2C%7B%22value%22%3A%22MxIF%22%2C%22label%22%3A%22MxIF%22%2C%22group%22%3A%22assayName%22%2C%22count%22%3A93%2C%22isSelected%22%3Afalse%7D%5D&tab=file

Also flagging @adamjtaylor to see if he may now.

**Comment by adamjtaylor** [comment]
Thanks @ecerami  - I'm aware of Vanderbilt missing some thumbnails and minerva images - For the H&E this was due to some out-of-memory errors due to the uncompressed and very large H&E files they provided. For the MxIF this was due to some valid but non-standard formatting within the tiff file - I will re-put on my to-do list to get these made manually (and more generally to get back up to date with other Atlas's where we are missing imaging resources.

Assigning to me until resolved.
