### ISSUE TITLE
Biospecimen file contains demographics data

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#45]
If I go to:  https://htan-portal-nextjs.now.sh/atlas/hta2

and click the tab "Clinical Biospecimen"

and then click Biospecimen Tier 1

I see a table with Demographics data.

**Comment by milen-sage** [comment]
This will get updated - I used demographics data for the biospecimen category since we didn't have the biospecimen attributes or fake data at the time. However, we now have most of the biospecimen attributes in the schema, and I'll input some biospecimen fake data to replace the demographics data. 

Just want to see how the current json (from #53) is parsed in the portal first, in case there are other higher priority changes we'd want to make.
