### ISSUE TITLE
Send some sample single cell links to Milen

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#49]
Send some sample single cell links to Milen

**Comment by milen-sage** [comment]
@inodb and @alisman - see PR #53

@inodb note the json in the PR ^ incorporates the link/other fake metadata you provided for sc level 4 visualization. However there are changes compared to the json in your PR #43 : scRNA-seq level 4 is added as *its own* category under assayData (scRNA-seq Assay is it's own separate category under assayData as well). This is consistent with how we handle other assay types as well. Because of these changes, there could be conflicts for data.json in #53 and #43 - something to be aware of.
