### ISSUE TITLE
Display data model version on Standards page

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/htan-portal#517]
Per [HTAN-198](https://sagebionetworks.jira.com/browse/HTAN-198) it would be great to

1. Display the version number and link to the data model release on GitHub on the standards page
2. Automate updating of the standards page when a new data model release is made.

**Comment by onursumer** [comment]
@adamjtaylor Seems like we are always fetching the latest data model from the main branch of https://github.com/ncihtan/data-models

https://github.com/ncihtan/htan-portal/blob/8b67e0ad616bc9fef6b3fc2f60f039e31a254634/lib/dataSchemaHelpers.ts#L195-L196

Do we want to change this so that we get the latest released version instead? Since we are already dynamically fetching the model from Github we can also get the release version number the same way. This would mean that we automatically display the correct version number for every new release.

**Comment by adamjtaylor** [comment]
Hey @onursumer. Thanks for looking into this. Yes let's point towards the latest released version and post the version number. Does this get updated "live" or does the portal need to be redeployed to update the data model display?

**Comment by onursumer** [comment]
Hi @adamjtaylor, let me know if #520 would work. You can preview it at https://htan-portal-nextjs-4ksxfdidr-htan.vercel.app/standards.
