### ISSUE TITLE
Add Treatment filter

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#625]
We have more treatment metadata now and it would be nice to add this in as a filter:

- [ ] Design treatment dropdown
- [ ] Implement treatment dropdown

**Comment by SAHU-01** [comment]
When you mentioned a treatment filter were to referring to something like this?
<img width="1511" alt="image" src="https://github.com/ncihtan/htan-portal/assets/71656941/61321426-5786-4b66-8ab8-d14150e55b86">

**Comment by onursumer** [comment]
@SAHU-01 Yes, it should look something like this. We may need to curate/normalize the values though. For example, we we should probably only list `Chemotherapy` as a filter value instead of `Surgery, Chemotherapy` because `Surgery` is already listed as a separate value.

> When you mentioned a treatment filter were to referring to something like this? <img alt="image" width="1511" src="https://private-user-images.githubusercontent.com/71656941/327322871-61321426-5786-4b66-8ab8-d14150e55b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzE4NTksIm5iZiI6MTcxNDY3MTU1OSwicGF0aCI6Ii83MTY1Njk0MS8zMjczMjI4NzEtNjEzMjE0MjYtNTc4Ni00YjY2LThhYjgtZDE0MTUwZTU1Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE3MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMzc0MjIzOTQzYWMxNDQyMGJmMTg1YzUyYWM2NDcyNGZiNzAyOGViN2EzZmZiM2Q3OWZhYzY2OWE3ZWNkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yM7ENaPYHFU74bLdyyoF1eGGA67DIr06NkXdKZBFf9Y">

**Comment by SAHU-01** [comment]
@onursumer regarding the normalization would this work?
<img width="1512" alt="image" src="https://github.com/ncihtan/htan-portal/assets/71656941/8e000149-c136-48dc-acec-eaba2099fc05">

**Comment by onursumer** [comment]
@SAHU-01 Yes, a list like that would work!

**Comment by onursumer** [comment]
@SAHU-01 Functionality looks good but we should have more than two treatment values (`Chemotherapy` and `Surgery`). There is `Therapy` information in `syn_data.json` which we haven't processed into `processed_syn_data.json` yet. We will need to modify [processSynapseJson.ts](https://github.com/ncihtan/htan-portal/blob/master/data/processSynapseJSON.ts) to include more treatment data in the `processed_syn_data.json` file.

We can probably generate a `therapyByParticipantID` or something similar so that we can use it to construct the treatment dropdown in the front end.
